//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTN.KTNServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegionsType", Namespace="http://schemas.datacontract.org/2004/07/SERVICE")]
    public enum RegionsType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COUNTRIES = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CITIES = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISTRICTS = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegionDto", Namespace="http://schemas.datacontract.org/2004/07/SERVICE.Dtos")]
    [System.SerializableAttribute()]
    public partial class RegionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> P_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REGION_NAMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> P_ID {
            get {
                return this.P_IDField;
            }
            set {
                if ((this.P_IDField.Equals(value) != true)) {
                    this.P_IDField = value;
                    this.RaisePropertyChanged("P_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REGION_NAME {
            get {
                return this.REGION_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.REGION_NAMEField, value) != true)) {
                    this.REGION_NAMEField = value;
                    this.RaisePropertyChanged("REGION_NAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDto", Namespace="http://schemas.datacontract.org/2004/07/SERVICE.Dtos")]
    [System.SerializableAttribute()]
    public partial class PersonDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIRST_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LAST_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KTN.KTNServiceRef.RegionDto REGIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIRST_NAME {
            get {
                return this.FIRST_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FIRST_NAMEField, value) != true)) {
                    this.FIRST_NAMEField = value;
                    this.RaisePropertyChanged("FIRST_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LAST_NAME {
            get {
                return this.LAST_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.LAST_NAMEField, value) != true)) {
                    this.LAST_NAMEField = value;
                    this.RaisePropertyChanged("LAST_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KTN.KTNServiceRef.RegionDto REGION {
            get {
                return this.REGIONField;
            }
            set {
                if ((object.ReferenceEquals(this.REGIONField, value) != true)) {
                    this.REGIONField = value;
                    this.RaisePropertyChanged("REGION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/SERVICE.Dtos")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIRST_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LAST_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERNAMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIRST_NAME {
            get {
                return this.FIRST_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FIRST_NAMEField, value) != true)) {
                    this.FIRST_NAMEField = value;
                    this.RaisePropertyChanged("FIRST_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LAST_NAME {
            get {
                return this.LAST_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.LAST_NAMEField, value) != true)) {
                    this.LAST_NAMEField = value;
                    this.RaisePropertyChanged("LAST_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERNAME {
            get {
                return this.USERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.USERNAMEField, value) != true)) {
                    this.USERNAMEField = value;
                    this.RaisePropertyChanged("USERNAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KTNServiceRef.IKTNService")]
    public interface IKTNService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKTNService/GetRegions", ReplyAction="http://tempuri.org/IKTNService/GetRegionsResponse")]
        KTN.KTNServiceRef.RegionDto[] GetRegions(KTN.KTNServiceRef.RegionsType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKTNService/GetRegions", ReplyAction="http://tempuri.org/IKTNService/GetRegionsResponse")]
        System.Threading.Tasks.Task<KTN.KTNServiceRef.RegionDto[]> GetRegionsAsync(KTN.KTNServiceRef.RegionsType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKTNService/GetPersons", ReplyAction="http://tempuri.org/IKTNService/GetPersonsResponse")]
        KTN.KTNServiceRef.PersonDto[] GetPersons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKTNService/GetPersons", ReplyAction="http://tempuri.org/IKTNService/GetPersonsResponse")]
        System.Threading.Tasks.Task<KTN.KTNServiceRef.PersonDto[]> GetPersonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKTNService/GetUser", ReplyAction="http://tempuri.org/IKTNService/GetUserResponse")]
        KTN.KTNServiceRef.UserDto GetUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKTNService/GetUser", ReplyAction="http://tempuri.org/IKTNService/GetUserResponse")]
        System.Threading.Tasks.Task<KTN.KTNServiceRef.UserDto> GetUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKTNService/GetUserByUsername", ReplyAction="http://tempuri.org/IKTNService/GetUserByUsernameResponse")]
        KTN.KTNServiceRef.UserDto GetUserByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKTNService/GetUserByUsername", ReplyAction="http://tempuri.org/IKTNService/GetUserByUsernameResponse")]
        System.Threading.Tasks.Task<KTN.KTNServiceRef.UserDto> GetUserByUsernameAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKTNServiceChannel : KTN.KTNServiceRef.IKTNService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KTNServiceClient : System.ServiceModel.ClientBase<KTN.KTNServiceRef.IKTNService>, KTN.KTNServiceRef.IKTNService {
        
        public KTNServiceClient() {
        }
        
        public KTNServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KTNServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KTNServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KTNServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KTN.KTNServiceRef.RegionDto[] GetRegions(KTN.KTNServiceRef.RegionsType type) {
            return base.Channel.GetRegions(type);
        }
        
        public System.Threading.Tasks.Task<KTN.KTNServiceRef.RegionDto[]> GetRegionsAsync(KTN.KTNServiceRef.RegionsType type) {
            return base.Channel.GetRegionsAsync(type);
        }
        
        public KTN.KTNServiceRef.PersonDto[] GetPersons() {
            return base.Channel.GetPersons();
        }
        
        public System.Threading.Tasks.Task<KTN.KTNServiceRef.PersonDto[]> GetPersonsAsync() {
            return base.Channel.GetPersonsAsync();
        }
        
        public KTN.KTNServiceRef.UserDto GetUser(string username, string password) {
            return base.Channel.GetUser(username, password);
        }
        
        public System.Threading.Tasks.Task<KTN.KTNServiceRef.UserDto> GetUserAsync(string username, string password) {
            return base.Channel.GetUserAsync(username, password);
        }
        
        public KTN.KTNServiceRef.UserDto GetUserByUsername(string username) {
            return base.Channel.GetUserByUsername(username);
        }
        
        public System.Threading.Tasks.Task<KTN.KTNServiceRef.UserDto> GetUserByUsernameAsync(string username) {
            return base.Channel.GetUserByUsernameAsync(username);
        }
    }
}
